language: python

python:
   - 3.6

dist: bionic

branches:
  only:
  - master
  - development

install:
#  - sudo apt-get update -y

  # install with conda and pip
  - pip install codecov
  - pip install -r requirements.txt
  - pip install .

before_script:
  - git config --global user.email "caseyjlaw@gmail.com"
  - git config --global user.name "Travis-CI"

script: 
  - coverage run --source antpos -m py.test

after_success:
  - coverage report
  - codecov --token=e8064661-6821-441b-b73b-678a1df0a516

notifications:
  email: false
#  slack: realfastvla:ID1qIFG70HGYf3G6Y3oWoFFk
